### ISSUE TITLE
DB configuration

### ISSUE THREAD

**Issue by freezed** [remace/OC-P8-Purbeurre#2]
# Issue

I notice this project run's [`django`](https://www.djangoproject.com/), and I made a local installation.
However, a `testserver` run crash:

```
$ ./manage.py testserver                                                                                                                           ✔  826  22:59:12
Creating test database for alias 'default'...
~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/postgresql/base.py:304: RuntimeWarning: Normally Django will use a connection to the 'postgres' database to avoid running initialization queries against the production database when it's not needed (for example, when running tests). Django was unable to create a connection to the 'postgres' database and will use the first PostgreSQL database instead.
  warnings.warn(
Traceback (most recent call last):
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »
FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 301, in _nodb_cursor
    with super()._nodb_cursor() as cursor:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 620, in _nodb_cursor
    with conn.cursor() as cursor:
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »
FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »
FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/git/men-rt-ocp08/./manage.py", line 22, in <module>
    main()
  File "~/git/men-rt-ocp08/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/core/management/commands/testserver.py", line 34, in handle
    db_name = connection.creation.create_test_db(verbosity=verbosity, autoclobber=not interactive, serialize=False)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/creation.py", line 57, in create_test_db
    self._create_test_db(verbosity, autoclobber, keepdb)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/creation.py", line 191, in _create_test_db
    with self._nodb_cursor() as cursor:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 319, in _nodb_cursor
    with conn.cursor() as cursor:
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "~/.venvs/men-rt-ocp08/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »
FATAL:  authentification par mot de passe échouée pour l'utilisateur  « Nutella_user »

zsh: exit 1     ./manage.py testserver
```

**Comment by remace** [comment]
you should configure a postgresql server, with a database 'Nutella_db', owned by an user 'Nutella_user' with password 'Nutella_pwd' (capitals important, so use quotes). Nutella_user must have database creation rights too.

i'll document this later

**Comment by remace** [comment]
create a database user called 'Nutella_user' and give him the rights to create a database as I posted it in readme.md
